// CommonTag type as union of allowed tags
import {Locale} from "@/i18n/types";

export const COMMON_TAGS = [
    "brand",
    "operator",
    "repair",
    "repair:*",
    "self_service",
    "fee",
    "lanes",
    "pet-friendly",
    "socket_type",
    "capacity",
    "fuel:*",
    "shop",
    "payment:*",
    "access",
    "covered",
    "toilets",
    "vending",
    "socket:type*",
    "restaurant",
    "produce",
    "organic",
    "grades",
    "faculty",
    "departments",
    "internet_access",
    "botanical",
    "soundproof",
    "screen",
    "hiking",
    "theme",
    "species",
    "gender",
    "nudity",
    "unisex",
    "currency",
    "cuisine",
    "diet",
    "wheelchair",
    "smoking",
    "outdoor_seating",
    "brewery",
    "happy_hours",
    "drive_through",
    "appointment",
    "services",
    "emergency",
    "beds",
    "schedule",
    "instructor",
    "floors",
    "units",
    "stars",
    "check_in",
    "shared_rooms",
    "price_range",
    "owner",
    "denomination",
    "service_times",
    "local_meat",
    "second_hand",
    "24_7",
    "equipment",
    "trainer",
    "personal_trainer",
    "indoor",
    "heated",
    "length",
    "routes",
    "shelter",
    "playground",
    "lines",
    "iata",
    "icao",
    "terminals",
    "bulk_purchase",
    "prescriptions",
    "booking",
    "wine-shop",
    "lgbt"
] as const;

export type CommonTag = typeof COMMON_TAGS[number];

export const COMMON_TAG_TRANSLATIONS: Record<Locale, Record<CommonTag, string>> = {
    en: {
        brand: "Brand",
        operator: "Operator",
        "pet-friendly": "Pet-friendly",
        repair: "Repair Type",
        "repair:*": "Specific Repair Type",
        self_service: "Self Service",
        fee: "Fee",
        "wheelchair": "Wheelchair accessible",
        "lanes": 'Lanes',
        "socket:type*": "Socket Type",
        socket_type: "Socket Type",
        capacity: "Capacity",
        "fuel:*": "Fuel Type",
        shop: "Shop",
        "payment:*": "Payment Methods",
        access: "Access",
        covered: "Covered",
        toilets: "Toilets",
        vending: "Vending",
        restaurant: "Restaurant",
        produce: "Produce",
        organic: "Organic",
        grades: "Grades",
        faculty: "Faculty",
        departments: "Departments",
        internet_access: "Internet Access",
        botanical: "Botanical",
        soundproof: "Soundproof",
        screen: "Screen",
        hiking: "Hiking",
        theme: "Theme",
        species: "Species",
        gender: "Gender",
        nudity: "Nudity",
        unisex: "Unisex",
        currency: "Currency",
        cuisine: "Cuisine",
        diet: "Diet",
        smoking: "Smoking",
        outdoor_seating: "Outdoor Seating",
        brewery: "Brewery",
        happy_hours: "Happy Hours",
        drive_through: "Drive-through",
        appointment: "Appointment",
        services: "Services",
        emergency: "Emergency",
        beds: "Beds",
        schedule: "Schedule",
        instructor: "Instructor",
        floors: "Floors",
        units: "Units",
        stars: "Stars",
        check_in: "Check-in",
        shared_rooms: "Shared Rooms",
        price_range: "Price Range",
        owner: "Owner",
        denomination: "Denomination",
        service_times: "Service Times",
        local_meat: "Local Meat",
        second_hand: "Second Hand",
        "24_7": "24/7",
        equipment: "Equipment",
        trainer: "Trainer",
        personal_trainer: "Personal Trainer",
        indoor: "Indoor",
        heated: "Heated",
        length: "Length",
        routes: "Routes",
        shelter: "Shelter",
        playground: 'Playground',
        lines: "Lines",
        iata: "IATA Code",
        icao: "ICAO Code",
        terminals: "Terminals",
        "bulk_purchase": "Bulk purchase",
        "prescriptions": "Prescriptions",
        "booking": "Booking",
        "wine-shop": "Wine shop",
        "lgbt": "LGBT-friendly"
    },
    es: {
        brand: "Marca",
        operator: "Operador",
        "pet-friendly": "Admite mascotas",
        repair: "Tipo de reparación",
        "repair:*": "Tipo de reparación específica",
        self_service: "Autoservicio",
        fee: "Tarifa",
        "wheelchair": "Accesible en sillas de ruedas",
        "lanes": 'Vías',
        socket_type: "Tipo de enchufe",
        "socket:type*": "Tipo de enchufe",
        capacity: "Capacidad",
        "fuel:*": "Tipo de combustible",
        shop: "Tienda",
        "payment:*": "Métodos de pago",
        access: "Acceso",
        covered: "Cubierto",
        toilets: "Baños",
        vending: "Máquinas expendedoras",
        restaurant: "Restaurante",
        produce: "Productos",
        organic: "Orgánico",
        grades: "Grados",
        faculty: "Facultad",
        departments: "Departamentos",
        internet_access: "Acceso a internet",
        botanical: "Botánico",
        soundproof: "Aislado acústicamente",
        screen: "Pantalla",
        hiking: "Senderismo",
        theme: "Temática",
        species: "Especies",
        gender: "Género",
        nudity: "Desnudez",
        unisex: "Unisex",
        currency: "Moneda",
        cuisine: "Tipo de cocina",
        diet: "Dieta",
        smoking: "Fumar",
        outdoor_seating: "Asientos al aire libre",
        brewery: "Cervecería",
        happy_hours: "Hora feliz",
        drive_through: "Auto-servicio",
        appointment: "Cita",
        services: "Servicios",
        emergency: "Emergencia",
        beds: "Camas",
        schedule: "Horario",
        instructor: "Instructor",
        floors: "Pisos",
        units: "Unidades",
        stars: "Estrellas",
        check_in: "Ingreso",
        shared_rooms: "Habitaciones compartidas",
        price_range: "Rango de precios",
        owner: "Dueño",
        denomination: "Denominación",
        service_times: "Horarios de servicio",
        local_meat: "Carne local",
        second_hand: "Segunda mano",
        "24_7": "24/7",
        equipment: "Equipamiento",
        trainer: "Entrenador",
        personal_trainer: "Entrenador personal",
        indoor: "Interior",
        heated: "Calefaccionado",
        length: "Longitud",
        routes: "Rutas",
        shelter: "Refugio",
        playground: 'Plaza de Juegos',
        lines: "Líneas",
        iata: "Código IATA",
        icao: "Código ICAO",
        terminals: "Terminales",
        "bulk_purchase": "Compra al por mayor",
        "prescriptions": "Prescripciones",
        "booking": "Reservas",
        "wine-shop": "Bodega",
        "lgbt": "LGBT-amigable"
    }
};
