// Simplified country names
import slugify from 'slugify';
import {PlaceSubcategory} from "@/constants/PlaceCategories";
import {Locale} from "@/i18n/types";

const simplifiedCountryNamesRaw = {
    'Russian Federation': 'Russia',
    'United States of America': 'United States',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Korea, Republic of': 'South Korea',
    'Iran, Islamic Republic of': 'Iran',
    'Venezuela, Bolivarian Republic of': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Syrian Arab Republic': 'Syria',
    'Bolivia, Plurinational State of': 'Bolivia',
    'Tanzania, United Republic of': 'Tanzania',
    'Moldova, Republic of': 'Moldova',
    'Macedonia, the former Yugoslav Republic of': 'North Macedonia',
    "Lao People's Democratic Republic": 'Laos',
    "Lao People\u2019s Democratic Republic": 'Laos',
    "C\u00f4te d'Ivoire": 'Ivory Coast',
    "Cote d'Ivoire": 'Ivory Coast',
    "People's Republic of China": 'China',
    'Palestine, State of': 'Palestine',
    'Brunei Darussalam': 'Brunei',
    'Czech Republic': 'Czechia',
    'Myanmar': 'Burma'
};

const simplifiedCountryNames = Object.fromEntries(
    Object.entries(simplifiedCountryNamesRaw).map(([key, val]) => [
        slugify(key, { lower: true, strict: true }).toLowerCase(),
        slugify(val, { lower: true, strict: true }).toLowerCase()
    ])
);

export function getSimplifiedCountrySlug(countryName: string): string {
    const simplified = simplifiedCountryNames[slugify(countryName, { lower: true, strict: true })];
    return simplified || slugify(countryName, { lower: true, strict: true });
}

export function getSimplifiedCitySlug(countryName: string, cityName: string): string {
    const simplifiedSlug = getSimplifiedCountrySlug(countryName);
    return `${slugify(cityName, { lower: true, strict: true }).toLowerCase()}-${simplifiedSlug}`;
}

export function getLocalizedCountrySlug(countryName: string, locale: string = 'en'): string {
    const slug = getSimplifiedCountrySlug(countryName)
    switch (locale) {
        case 'es': return `lugares-bitcoin-en-${slug}`;
        case 'pt': return `locais-bitcoin-em-${slug}`;
        default: return `bitcoin-shops-in-${slug}`;
    }
}

// === Manual plural slug maps ===
const SUBCATEGORY_ES_SLUG_MAP: Record<PlaceSubcategory, string> = {
    // transporation
    airport: 'aeropuertos',
    airstrip: 'pistas-de-aterrizaje',
    bus_station: 'estaciones-de-autobuses',
    bus_stop: 'paradas-de-autobus',
    ferry_terminal: 'terminales-de-ferry',
    heliport: 'helipuertos',
    international_airport: 'aeropuertos-internacionales',
    light_rail_station: 'estaciones-de-tren-ligero',
    park_and_ride: 'estacionamientos-con-transporte',
    subway_station: 'estaciones-de-metro',
    taxi_stand: 'paradas-de-taxi',
    train_station: 'estaciones-de-tren',
    transit_depot: 'depositos-de-transporte',
    transit_station: 'estaciones-de-transporte',
    truck_stop: 'paradas-de-camiones',

    //sports
    dojo: 'dojos',
    water_sports: 'deportes-de-agua',
    surf_school: 'escuelas-de-surf',
    arena: 'estadios-cubiertos',
    athletic_field: 'campos-deportivos',
    fishing_charter: 'excursiones-de-pesca',
    fishing_pond: 'estanques-de-pesca',
    fitness_center: 'centros-de-acondicionamiento-fisico',
    golf_course: 'campos-de-golf',
    gym: 'gimnasios',
    ice_skating_rink: 'pistas-de-patinaje-sobre-hielo',
    playground: 'areas-de-juego',
    ski_resort: 'estaciones-de-esqui',
    sports_activity_location: 'lugares-de-actividad-deportiva',
    sports_club: 'clubes-deportivos',
    sports_coaching: 'entrenamientos-deportivos',
    sports_complex: 'complejos-deportivos',
    stadium: 'estadios',
    swimming_pool: 'piscinas',

    // shopping
    tobacco: "tiendas-de-tabaco",
    second_hand: 'tiendas-de-articulos-usados',
    seafood_shop: "pescaderias",
    stationery_store: "papelerias",
    cannabis: "tiendas-de-cannabis",
    craft_store: "tiendas-de-manualidades",
    copyshop: "centros-de-copiado",
    gardening_store: "tiendas-de-jardineria",
    asian_grocery_store: "tiendas-de-comestibles-asiaticos",
    auto_parts_store: "tiendas-de-repuestos-de-autos",
    bicycle_store: "tiendas-de-bicicletas",
    book_store: "librerias",
    butcher_shop: "carnicerias",
    cell_phone_store: "tiendas-de-celulares",
    clothing_store: "tiendas-de-ropa",
    convenience_store: "tiendas-de-conveniencia",
    department_store: "tiendas-por-departamentos",
    discount_store: "tiendas-de-descuentos",
    electronics_store: "tiendas-de-electronica",
    food_store: "tiendas-de-alimentos",
    furniture_store: "mueblerias",
    gift_shop: "tiendas-de-regalos",
    grocery_store: "supermercados",
    hardware_store: "ferreterias",
    home_goods_store: "tiendas-de-articulos-para-el-hogar",
    home_improvement_store: "tiendas-de-mejoras-del-hogar",
    jewelry_store: "joyerias",
    liquor_store: "licorerias",
    market: "mercados",
    music_store: "tiendas-de-musica",
    pet_store: "tiendas-de-mascotas",
    optician: "opticas",
    shoe_store: "zapaterias",
    shopping_mall: "centros-comerciales",
    sporting_goods_store: "tiendas-de-deportes",
    store: "tiendas",
    supermarket: "supermercados",
    warehouse_store: "tiendas-mayoristas",
    wholesaler: "mayoristas",

    //services

    "3d-printing": "servicios-de-impresion-3d",
    advertising: "servicios-de-publicidad",
    architect: "arquitectos",
    cleaning: "limpiadores",
    graphic_design: "servicios-de-diseno-grafico",
    gardener: "jardineros",
    photographer: "fotografos",
    beekeeper: "cuidadores-de-abejas",
    carpenter: "carpinteros",
    astrologer: "astrologos",
    barber_shop: "barberias",
    beautician: "esteticistas",
    beauty_salon: "salones-de-belleza",
    body_art_service: "servicios-de-arte-corporal",
    catering_service: "servicios-de-catering",
    cemetery: "cementerios",
    child_care_agency: "agencias-de-cuidado-infantil",
    consultant: "consultores",
    contractor: "contratistas",
    courier_service: "servicios-de-mensajeria",
    electrician: "electricistas",
    florist: "floristerias",
    food_delivery: "servicios-de-entrega-de-comida",
    foot_care: "servicios-de-cuidado-de-pies",
    funeral_home: "funerarias",
    hair_care: "servicios-de-cuidado-del-cabello",
    hair_salon: "peluquerias",
    insurance_agency: "agencias-de-seguros",
    laundry: "lavanderias",
    lawyer: "abogados",
    locksmith: "cerrajeros",
    makeup_artist: "maquilladores",
    moving_company: "empresas-de-mudanzas",
    nail_salon: "salones-de-unas",
    painter: "pintores",
    plumber: "plomeros",
    psychic: "psiquicos",
    real_estate_agency: "agencias-inmobiliarias",
    roofing_contractor: "contratistas-de-techos",
    storage: "depositos",
    summer_camp_organizer: "organizadores-de-campamentos-de-verano",
    tailor: "sastres",
    telecommunications_service_provider: "proveedores-de-servicios-de-telecomunicaciones",
    tour_agency: "agencias-de-turismo",
    tourist_information_center: "centros-de-informacion-turistica",
    travel_agency: "agencias-de-viajes",
    veterinary_care: "centros-de-atencion-veterinaria",

    // Lodging
    bed_and_breakfast: 'camas-y-desayunos',
    budget_japanese_inn: 'posadas-japonesas-economicas',
    chalet: 'chalets',
    campground: 'campamentos',
    camping_cabin: 'cabanas-de-camping',
    cottage: 'cabanas',
    extended_stay_hotel: 'hoteles-de-estadia-prolongada',
    farmstay: 'alojamientos-en-granja',
    guest_house: 'casas-de-huespedes',
    hostel: 'hostales',
    hotel: 'hoteles',
    inn: 'posadas',
    japanese_inn: 'posadas-japonesas',
    lodging: 'alojamientos',
    mobile_home_park: 'parques-de-casas-rodantes',
    motel: 'moteles',
    private_guest_room: 'habitaciones-privadas-para-huespedes',
    resort_hotel: 'hoteles-resort',
    rv_park: 'parques-para-casas-rodantes',

    // Natural Features
    beach: 'playas',

    // Places of Worship
    church: 'iglesias',
    hindu_temple: 'templos-hindues',
    mosque: 'mezquitas',
    synagogue: 'sinagogas',

    // Geographical Areas
    administrative_area_level_1: 'areas-administrativas-nivel-1',
    administrative_area_level_2: 'areas-administrativas-nivel-2',
    country: 'paises',
    locality: 'localidades',
    postal_code: 'codigos-postales',
    school_district: 'distritos-escolares',

    // Government
    city_hall: 'ayuntamientos',
    courthouse: 'palacios-de-justicia',
    embassy: 'embajadas',
    fire_station: 'estaciones-de-bomberos',
    government_office: 'oficinas-gubernamentales',
    local_government_office: 'oficinas-del-gobierno-local',
    neighborhood_police_station: 'comisarias-de-barrio',
    police: 'comisarias',
    post_office: 'oficinas-de-correos',

    // Health and Wellness
    alternative_medicine: 'centros-de-medicina-alternativa',
    psychotherapist: 'psicoterapeutas',
    chiropractor: 'quiropracticos',
    clinic: 'clinicas',
    dental_clinic: 'clinicas-dentales',
    dentist: 'dentistas',
    doctor: 'medicos',
    drugstore: 'farmacias',
    hospital: 'hospitales',
    massage: 'centros-de-masajes',
    medical_lab: 'laboratorios-medicos',
    pharmacy: 'farmacias',
    physiotherapist: 'fisioterapeutas',
    sauna: 'saunas',
    skin_care_clinic: 'clinicas-de-cuidado-de-la-piel',
    spa: 'spas',
    tanning_studio: 'centros-de-bronceado',
    wellness_center: 'centros-de-bienestar',
    yoga_studio: 'estudios-de-yoga',

    // Housing
    apartment_building: 'edificios-de-apartamentos',
    apartment_complex: 'complejos-de-apartamentos',
    condominium_complex: 'complejos-de-condominios',
    housing_complex: 'conjuntos-habitacionales',


    acai_shop: 'tiendas-de-acai',
    afghani_restaurant: 'restaurantes-afganos',
    african_restaurant: 'restaurantes-africanos',
    american_restaurant: 'restaurantes-americanos',
    asian_restaurant: 'restaurantes-asiaticos',
    bagel_shop: 'tiendas-de-bagels',
    bakery: 'panaderias',
    bar: 'bares',
    bar_and_grill: 'bares-y-parrillas',
    barbecue_restaurant: 'restaurantes-de-barbacoa',
    brazilian_restaurant: 'restaurantes-brasilenos',
    breakfast_restaurant: 'restaurantes-de-desayunos',
    brunch_restaurant: 'restaurantes-de-brunch',
    buffet_restaurant: 'restaurantes-buffet',
    cafe: 'cafes',
    cafeteria: 'cafeterias',
    candy_store: 'tiendas-de-dulces',
    cat_cafe: 'cafes-con-gatos',
    chinese_restaurant: 'restaurantes-chinos',
    chocolate_factory: 'fabricas-de-chocolate',
    chocolate_shop: 'tiendas-de-chocolate',
    coffee_shop: 'cafeterias',
    confectionery: 'confiterias',
    deli: 'delicatessen',
    dessert_restaurant: 'restaurantes-de-postres',
    dessert_shop: 'tiendas-de-postres',
    diner: 'cafeterias-americanas',
    dog_cafe: 'cafes-con-perros',
    donut_shop: 'tiendas-de-donas',
    fast_food_restaurant: 'restaurantes-de-comida-rapida',
    fine_dining_restaurant: 'restaurantes-de-alta-cocina',
    food_court: 'patios-de-comidas',
    french_restaurant: 'restaurantes-franceses',
    greek_restaurant: 'restaurantes-griegos',
    hamburger_restaurant: 'hamburgueserias',
    ice_cream_shop: 'heladerias',
    indian_restaurant: 'restaurantes-indios',
    indonesian_restaurant: 'restaurantes-indonesios',
    italian_restaurant: 'restaurantes-italianos',
    japanese_restaurant: 'restaurantes-japoneses',
    juice_shop: 'tiendas-de-jugos',
    korean_restaurant: 'restaurantes-coreanos',
    lebanese_restaurant: 'restaurantes-libaneses',
    meal_delivery: 'servicios-de-entrega-de-comida',
    meal_takeaway: 'lugares-de-comida-para-llevar',
    mediterranean_restaurant: 'restaurantes-mediterraneos',
    mexican_restaurant: 'restaurantes-mexicanos',
    middle_eastern_restaurant: 'restaurantes-de-medio-oriente',
    pizza_restaurant: 'pizzerias',
    pub: 'pubs',
    ramen_restaurant: 'restaurantes-de-ramen',
    restaurant: 'restaurantes',
    sandwich_shop: 'tiendas-de-sandwiches',
    seafood_restaurant: 'restaurantes-de-mariscos',
    spanish_restaurant: 'restaurantes-espanoles',
    steak_house: 'parrillas',
    sushi_restaurant: 'restaurantes-de-sushi',
    tea_house: 'casas-de-te',
    thai_restaurant: 'restaurantes-tailandeses',
    turkish_restaurant: 'restaurantes-turcos',
    vegan_restaurant: 'restaurantes-veganos',
    vegetarian_restaurant: 'restaurantes-vegetarianos',
    vietnamese_restaurant: 'restaurantes-vietnamitas',
    wine_bar: 'bares-de-vinos',

    // === Instalaciones ===
    "public_bath": "baños-publicos",
    "public_bathroom": "sanitarios-publicos",
    "stable": "establos",

// === Finanzas ===
    "accounting": "contadurias",
    "atm": "cajeros-automaticos",
    "bank": "bancos",
    "currency_exchange": "casas-de-cambio",
    // === Entretenimiento y Recreación ===
    "adventure_sports_center": "centros-de-deportes-de-aventura",
    "amphitheatre": "anfiteatros",
    "amusement_center": "centros-de-entretenimiento",
    "amusement_park": "parques-de-diversiones",
    "aquarium": "acuarios",
    "banquet_hall": "salones-de-banquetes",
    "barbecue_area": "areas-de-barbacoa",
    "botanical_garden": "jardines-botanicos",
    "bowling_alley": "boleras",
    "casino": "casinos",
    "childrens_camp": "campamentos-infantiles",
    "comedy_club": "clubes-de-comedia",
    "community_center": "centros-comunitarios",
    "concert_hall": "salas-de-conciertos",
    "convention_center": "centros-de-convenciones",
    "cultural_center": "centros-culturales",
    "cycling_park": "parques-para-ciclismo",
    "dance_hall": "salas-de-baile",
    "dog_park": "parques-para-perros",
    "event_venue": "salones-de-eventos",
    "ferris_wheel": "norias",
    "garden": "jardines",
    "hiking_area": "zonas-de-senderismo",
    "historical_landmark": "sitios-historicos-emblematicos",
    "internet_cafe": "cibercafes",
    "karaoke": "karaokes",
    "marina": "marinas",
    "movie_rental": "alquileres-de-peliculas",
    "movie_theater": "cines",
    "national_park": "parques-nacionales",
    "night_club": "clubes-nocturnos",
    "observation_deck": "plataformas-de-observacion",
    "off_roading_area": "zonas-de-todoterreno",
    "opera_house": "casas-de-la-opera",
    "park": "parques",
    "philharmonic_hall": "salas-filarmonicas",
    "picnic_ground": "areas-de-picnic",
    "planetarium": "planetarios",
    "plaza": "plazas",
    "roller_coaster": "montanas-rusas",
    "skateboard_park": "parques-de-skate",
    "state_park": "parques-estatales",
    "tourist_attraction": "atracciones-turisticas",
    "video_arcade": "salas-de-videojuegos",
    "visitor_center": "centros-de-visitantes",
    "water_park": "parques-acuaticos",
    "wedding_venue": "salones-de-bodas",
    "wildlife_park": "parques-de-vida-silvestre",
    "wildlife_refuge": "refugios-de-vida-silvestre",
    "zoo": "zoologicos",

    // === Negocios ===
    corporate_office: "oficinas-corporativas",
    farm: "granjas",
    ranch: "ranchos",
    coworking_space: "espacios-coworking",

// === Cultura ===
    art_gallery: "galerias-de-arte",
    art_studio: "estudios-de-arte",
    auditorium: "auditorios",
    cultural_landmark: "lugares-emblematicos-culturales",
    historical_place: "lugares-historicos",
    monument: "monumentos",
    museum: "museos",
    performing_arts_theater: "teatros-de-artes-escenicas",
    sculpture: "esculturas",

// === Educación ===
    library: "bibliotecas",
    preschool: "jardines-de-infantes",
    primary_school: "escuelas-primarias",
    school: "escuelas",
    secondary_school: "escuelas-secundarias",
    university: "universidades",
    music_school: "escuelas-de-musica",
    driving_school: "escuelas-de-manejo",
    cooking_school: "escuelas-de-cocina",

// === Automotriz ===
    bicycle_rental: "rentas-de-bicicletas",
    car_dealer: "concesionarios-de-autos",
    car_rental: "alquileres-de-autos",
    car_repair: "talleres-mecanicos",
    car_wash: "lavados-de-autos",
    electric_vehicle_charging_station: "estaciones-de-carga-para-vehiculos-electricos",
    gas_station: "estaciones-de-servicio",
    parking: "estacionamientos",
    rest_stop: "areas-de-descanso",

    // other
    other: "otros",
};

const SUBCATEGORY_EN_SLUG_MAP: Record<PlaceSubcategory, string> = {

    // transportation
    airport: 'airports',
    airstrip: 'airstrips',
    bus_station: 'bus-stations',
    bus_stop: 'bus-stops',
    ferry_terminal: 'ferry-terminals',
    heliport: 'heliports',
    international_airport: 'international-airports',
    light_rail_station: 'light-rail-stations',
    park_and_ride: 'park-and-rides',
    subway_station: 'subway-stations',
    taxi_stand: 'taxi-stands',
    train_station: 'train-stations',
    transit_depot: 'transit-depots',
    transit_station: 'transit-stations',
    truck_stop: 'truck-stops',
    // sports

    dojo: 'dojos',
    water_sports: 'water-sports',
    surf_school: 'surf-schools',
    arena: 'indoor-arenas',
    athletic_field: 'athletic-fields',
    fishing_charter: 'fishing-charters',
    fishing_pond: 'fishing-ponds',
    fitness_center: 'fitness-centers',
    golf_course: 'golf-courses',
    gym: 'gyms',
    ice_skating_rink: 'ice-skating-rinks',
    playground: 'playgrounds',
    ski_resort: 'ski-resorts',
    sports_activity_location: 'sports-activity-locations',
    sports_club: 'sports-clubs',
    sports_coaching: 'sports-coaching-programs',
    sports_complex: 'sports-complexes',
    stadium: 'stadiums',
    swimming_pool: 'swimming-pools',

    // shopping
    tobacco: "tobacco-shops",
    seafood_shop: "seafood-shops",
    stationery_store: "stationery-stores",
    cannabis: "cannabis-dispensaries",
    craft_store: "craft-stores",
    second_hand: 'second-hand-store',
    copyshop: "copyshops",
    gardening_store: "gardening-stores",
    asian_grocery_store: "asian-grocery-stores",
    auto_parts_store: "auto-parts-stores",
    bicycle_store: "bicycle-stores",
    book_store: "bookstores",
    butcher_shop: "butcher-shops",
    cell_phone_store: "cell-phone-stores",
    clothing_store: "clothing-stores",
    convenience_store: "convenience-stores",
    department_store: "department-stores",
    discount_store: "discount-stores",
    electronics_store: "electronics-stores",
    food_store: "food-stores",
    furniture_store: "furniture-stores",
    gift_shop: "gift-shops",
    grocery_store: "grocery-stores",
    hardware_store: "hardware-stores",
    home_goods_store: "home-goods-stores",
    home_improvement_store: "home-improvement-stores",
    jewelry_store: "jewelry-stores",
    liquor_store: "liquor-stores",
    market: "markets",
    music_store: "music-stores",
    pet_store: "pet-stores",
    optician: "opticians",
    shoe_store: "shoe-stores",
    shopping_mall: "shopping-malls",
    sporting_goods_store: "sporting-goods-stores",
    store: "stores",
    supermarket: "supermarkets",
    warehouse_store: "warehouse-stores",
    wholesaler: "wholesalers",

    // services

    "3d-printing": "3d-printing-services",
    advertising: "advertising-services",
    architect: "architects",
    cleaning: "cleaners",
    graphic_design: "graphic-design-services",
    gardener: "gardeners",
    photographer: "photographers",
    beekeeper: "beekeepers",
    carpenter: "carpenters",
    astrologer: "astrologers",
    barber_shop: "barber-shops",
    beautician: "beauticians",
    beauty_salon: "beauty-salons",
    body_art_service: "body-art-services",
    catering_service: "catering-services",
    cemetery: "cemeteries",
    child_care_agency: "child-care-agencies",
    consultant: "consultants",
    contractor: "contractors",
    courier_service: "courier-services",
    electrician: "electricians",
    florist: "florists",
    food_delivery: "food-delivery-services",
    foot_care: "foot-care-services",
    funeral_home: "funeral-homes",
    hair_care: "hair-care-services",
    hair_salon: "hair-salons",
    insurance_agency: "insurance-agencies",
    laundry: "laundries",
    lawyer: "lawyers",
    locksmith: "locksmiths",
    makeup_artist: "makeup-artists",
    moving_company: "moving-companies",
    nail_salon: "nail-salons",
    painter: "painters",
    plumber: "plumbers",
    psychic: "psychics",
    real_estate_agency: "real-estate-agencies",
    roofing_contractor: "roofing-contractors",
    storage: "storage-facilities",
    summer_camp_organizer: "summer-camp-organizers",
    tailor: "tailors",
    telecommunications_service_provider: "telecommunications-service-providers",
    tour_agency: "tour-agencies",
    tourist_information_center: "tourist-information-centers",
    travel_agency: "travel-agencies",
    veterinary_care: "veterinary-care-centers",

    // Lodging
    bed_and_breakfast: 'bed-and-breakfasts',
    budget_japanese_inn: 'budget-japanese-inns',
    chalet: 'chalets',
    campground: 'campgrounds',
    camping_cabin: 'camping-cabins',
    cottage: 'cottages',
    extended_stay_hotel: 'extended-stay-hotels',
    farmstay: 'farmstays',
    guest_house: 'guest-houses',
    hostel: 'hostels',
    hotel: 'hotels',
    inn: 'inns',
    japanese_inn: 'japanese-inns',
    lodging: 'lodging-options',
    mobile_home_park: 'mobile-home-parks',
    motel: 'motels',
    private_guest_room: 'private-guest-rooms',
    resort_hotel: 'resort-hotels',
    rv_park: 'rv-parks',

    // Natural Features
    beach: 'beaches',

    // Places of Worship
    church: 'churches',
    hindu_temple: 'hindu-temples',
    mosque: 'mosques',
    synagogue: 'synagogues',

    // Geographical Areas
    administrative_area_level_1: 'administrative-areas-level-1',
    administrative_area_level_2: 'administrative-areas-level-2',
    country: 'countries',
    locality: 'localities',
    postal_code: 'postal-codes',
    school_district: 'school-districts',

    // Government
    city_hall: 'city-halls',
    courthouse: 'courthouses',
    embassy: 'embassies',
    fire_station: 'fire-stations',
    government_office: 'government-offices',
    local_government_office: 'local-government-offices',
    neighborhood_police_station: 'neighborhood-police-stations',
    police: 'police-stations',
    post_office: 'post-offices',

    // Health and Wellness
    alternative_medicine: 'alternative-medicine-centers',
    psychotherapist: 'psychotherapists',
    chiropractor: 'chiropractors',
    clinic: 'clinics',
    dental_clinic: 'dental-clinics',
    dentist: 'dentists',
    doctor: 'doctors',
    drugstore: 'drugstores',
    hospital: 'hospitals',
    massage: 'massage-centers',
    medical_lab: 'medical-labs',
    pharmacy: 'pharmacies',
    physiotherapist: 'physiotherapists',
    sauna: 'saunas',
    skin_care_clinic: 'skin-care-clinics',
    spa: 'spas',
    tanning_studio: 'tanning-studios',
    wellness_center: 'wellness-centers',
    yoga_studio: 'yoga-studios',

    // Housing
    apartment_building: 'apartment-buildings',
    apartment_complex: 'apartment-complexes',
    condominium_complex: 'condominium-complexes',
    housing_complex: 'housing-complexes',

    acai_shop: 'acai-shops',
    afghani_restaurant: 'afghani-restaurants',
    african_restaurant: 'african-restaurants',
    american_restaurant: 'american-restaurants',
    asian_restaurant: 'asian-restaurants',
    bagel_shop: 'bagel-shops',
    bakery: 'bakeries',
    bar: 'bars',
    bar_and_grill: 'bars-and-grills',
    barbecue_restaurant: 'barbecue-restaurants',
    brazilian_restaurant: 'brazilian-restaurants',
    breakfast_restaurant: 'breakfast-restaurants',
    brunch_restaurant: 'brunch-restaurants',
    buffet_restaurant: 'buffet-restaurants',
    cafe: 'cafes',
    cafeteria: 'cafeterias',
    candy_store: 'candy-stores',
    cat_cafe: 'cat-cafes',
    chinese_restaurant: 'chinese-restaurants',
    chocolate_factory: 'chocolate-factories',
    chocolate_shop: 'chocolate-shops',
    coffee_shop: 'coffee-shops',
    confectionery: 'confectioneries',
    deli: 'delis',
    dessert_restaurant: 'dessert-restaurants',
    dessert_shop: 'dessert-shops',
    diner: 'diners',
    dog_cafe: 'dog-cafes',
    donut_shop: 'donut-shops',
    fast_food_restaurant: 'fast-food-restaurants',
    fine_dining_restaurant: 'fine-dining-restaurants',
    food_court: 'food-courts',
    french_restaurant: 'french-restaurants',
    greek_restaurant: 'greek-restaurants',
    hamburger_restaurant: 'hamburger-restaurants',
    ice_cream_shop: 'ice-cream-shops',
    indian_restaurant: 'indian-restaurants',
    indonesian_restaurant: 'indonesian-restaurants',
    italian_restaurant: 'italian-restaurants',
    japanese_restaurant: 'japanese-restaurants',
    juice_shop: 'juice-shops',
    korean_restaurant: 'korean-restaurants',
    lebanese_restaurant: 'lebanese-restaurants',
    meal_delivery: 'meal-delivery-services',
    meal_takeaway: 'meal-takeaways',
    mediterranean_restaurant: 'mediterranean-restaurants',
    mexican_restaurant: 'mexican-restaurants',
    middle_eastern_restaurant: 'middle-eastern-restaurants',
    pizza_restaurant: 'pizza-restaurants',
    pub: 'pubs',
    ramen_restaurant: 'ramen-restaurants',
    restaurant: 'restaurants',
    sandwich_shop: 'sandwich-shops',
    seafood_restaurant: 'seafood-restaurants',
    spanish_restaurant: 'spanish-restaurants',
    steak_house: 'steak-houses',
    sushi_restaurant: 'sushi-restaurants',
    tea_house: 'tea-houses',
    thai_restaurant: 'thai-restaurants',
    turkish_restaurant: 'turkish-restaurants',
    vegan_restaurant: 'vegan-restaurants',
    vegetarian_restaurant: 'vegetarian-restaurants',
    vietnamese_restaurant: 'vietnamese-restaurants',
    wine_bar: 'wine-bars',
    // === Facilities ===
    "public_bath": "public-baths",
    "public_bathroom": "public-bathrooms",
    "stable": "stables",

// === Finance ===
    "accounting": "accounting-services",
    "atm": "atms",
    "bank": "banks",
    "currency_exchange": "currency-exchanges",
    // === Entertainment and Recreation ===
    "adventure_sports_center": "adventure-sports-centers",
    "amphitheatre": "amphitheatres",
    "amusement_center": "amusement-centers",
    "amusement_park": "amusement-parks",
    "aquarium": "aquariums",
    "banquet_hall": "banquet-halls",
    "barbecue_area": "barbecue-areas",
    "botanical_garden": "botanical-gardens",
    "bowling_alley": "bowling-alleys",
    "casino": "casinos",
    "childrens_camp": "childrens-camps",
    "comedy_club": "comedy-clubs",
    "community_center": "community-centers",
    "concert_hall": "concert-halls",
    "convention_center": "convention-centers",
    "cultural_center": "cultural-centers",
    "cycling_park": "cycling-parks",
    "dance_hall": "dance-halls",
    "dog_park": "dog-parks",
    "event_venue": "event-venues",
    "ferris_wheel": "ferris-wheels",
    "garden": "gardens",
    "hiking_area": "hiking-areas",
    "historical_landmark": "historical-landmarks",
    "internet_cafe": "internet-cafes",
    "karaoke": "karaoke-bars",
    "marina": "marinas",
    "movie_rental": "movie-rentals",
    "movie_theater": "movie-theaters",
    "national_park": "national-parks",
    "night_club": "night-clubs",
    "observation_deck": "observation-decks",
    "off_roading_area": "off-roading-areas",
    "opera_house": "opera-houses",
    "park": "parks",
    "philharmonic_hall": "philharmonic-halls",
    "picnic_ground": "picnic-grounds",
    "planetarium": "planetariums",
    "plaza": "plazas",
    "roller_coaster": "roller-coasters",
    "skateboard_park": "skateboard-parks",
    "state_park": "state-parks",
    "tourist_attraction": "tourist-attractions",
    "video_arcade": "video-arcades",
    "visitor_center": "visitor-centers",
    "water_park": "water-parks",
    "wedding_venue": "wedding-venues",
    "wildlife_park": "wildlife-parks",
    "wildlife_refuge": "wildlife-refuges",
    "zoo": "zoos",

    // === Business ===
    corporate_office: "corporate-offices",
    farm: "farms",
    ranch: "ranches",
    coworking_space: "coworking-spaces",

// === Culture ===
    art_gallery: "art-galleries",
    art_studio: "art-studios",
    auditorium: "auditoriums",
    cultural_landmark: "cultural-landmarks",
    historical_place: "historical-places",
    monument: "monuments",
    museum: "museums",
    performing_arts_theater: "performing-arts-theaters",
    sculpture: "sculptures",

// === Education ===
    library: "libraries",
    preschool: "preschools",
    primary_school: "primary-schools",
    school: "schools",
    secondary_school: "secondary-schools",
    university: "universities",
    music_school: "music-schools",
    driving_school: "driving-schools",
    cooking_school: "cooking-schools",

    // === Automotive ===
    bicycle_rental: "bicycle-rentals",
    car_dealer: "car-dealers",
    car_rental: "car-rentals",
    car_repair: "car-repair-shops",
    car_wash: "car-washes",
    electric_vehicle_charging_station: "ev-charging-stations",
    gas_station: "gas-stations",
    parking: "parking-lots",
    rest_stop: "rest-stops",

    // other
    other: "other",
};

const SUBCATEGORY_PT_SLUG_MAP: Record<PlaceSubcategory, string> = {
    // transporte
    airport: 'aeroportos',
    airstrip: 'pistas-de-pouso',
    bus_station: 'estacoes-de-onibus',
    bus_stop: 'paradas-de-onibus',
    ferry_terminal: 'terminais-de-ferry',
    heliport: 'heliportos',
    international_airport: 'aeroportos-internacionais',
    light_rail_station: 'estacoes-de-trem-leve',
    park_and_ride: 'estacionamentos-com-transporte',
    subway_station: 'estacoes-de-metro',
    taxi_stand: 'pontos-de-taxi',
    train_station: 'estacoes-de-trem',
    transit_depot: 'depositos-de-transporte',
    transit_station: 'estacoes-de-transporte',
    truck_stop: 'paradas-de-caminhoes',

    // esportes
    dojo: 'dojos',
    water_sports: 'esportes-aquaticos',
    surf_school: 'escolas-de-surf',
    arena: 'arenas-cobertas',
    athletic_field: 'campos-de-atletismo',
    fishing_charter: 'excursoes-de-pesca',
    fishing_pond: 'lagos-de-pesca',
    fitness_center: 'centros-de-fitness',
    golf_course: 'campos-de-golfe',
    gym: 'academias',
    ice_skating_rink: 'pistas-de-patinacao-no-gelo',
    playground: 'parquinhos',
    ski_resort: 'estacoes-de-esqui',
    sports_activity_location: 'locais-de-atividade-esportiva',
    sports_club: 'clubes-esportivos',
    sports_coaching: 'treinamentos-esportivos',
    sports_complex: 'complexos-esportivos',
    stadium: 'estadios',
    swimming_pool: 'piscinas',

    // compras
    tobacco: 'tabacarias',
    second_hand: 'brechos',
    seafood_shop: 'peixarias',
    stationery_store: 'papelarias',
    cannabis: 'lojas-de-cannabis',
    craft_store: 'lojas-de-artesanato',
    copyshop: 'copiadoras',
    gardening_store: 'lojas-de-jardinagem',
    asian_grocery_store: 'mercearias-asiaticas',
    auto_parts_store: 'lojas-de-autopecas',
    bicycle_store: 'lojas-de-bicicletas',
    book_store: 'livrarias',
    butcher_shop: 'acougues',
    cell_phone_store: 'lojas-de-celulares',
    clothing_store: 'lojas-de-roupas',
    convenience_store: 'lojas-de-conveniencia',
    department_store: 'lojas-de-departamento',
    discount_store: 'lojas-de-desconto',
    electronics_store: 'lojas-de-eletronica',
    food_store: 'lojas-de-alimentos',
    furniture_store: 'lojas-de-moveis',
    gift_shop: 'lojas-de-presentes',
    grocery_store: 'supermercados',
    hardware_store: 'lojas-de-ferragens',
    home_goods_store: 'lojas-de-artigos-para-casa',
    home_improvement_store: 'lojas-de-materiais-de-construcao',
    jewelry_store: 'joalherias',
    liquor_store: 'lojas-de-bebidas',
    market: 'mercados',
    music_store: 'lojas-de-musica',
    pet_store: 'pet-shops',
    optician: 'oticas',
    shoe_store: 'lojas-de-calcados',
    shopping_mall: 'shopping-centers',
    sporting_goods_store: 'lojas-de-artigos-esportivos',
    store: 'lojas',
    supermarket: 'supermercados',
    warehouse_store: 'atacadistas',
    wholesaler: 'distribuidores',

    // servicos
    "3d-printing": 'servicos-de-impressao-3d',
    advertising: 'servicos-de-publicidade',
    architect: 'arquitetos',
    cleaning: 'servicos-de-limpeza',
    graphic_design: 'servicos-de-design-grafico',
    gardener: 'jardineiros',
    photographer: 'fotografos',
    beekeeper: 'apicultores',
    carpenter: 'carpinteiros',
    astrologer: 'astrologos',
    barber_shop: 'barbearias',
    beautician: 'esteticistas',
    beauty_salon: 'saloes-de-beleza',
    body_art_service: 'servicos-de-arte-corporal',
    catering_service: 'servicos-de-buffet',
    cemetery: 'cemiterios',
    child_care_agency: 'agencias-de-cuidado-infantil',
    consultant: 'consultores',
    contractor: 'empreiteiros',
    courier_service: 'servicos-de-entrega',
    electrician: 'eletricistas',
    florist: 'floriculturas',
    food_delivery: 'servicos-de-delivery-de-comida',
    foot_care: 'servicos-de-podologia',
    funeral_home: 'funerarias',
    hair_care: 'servicos-de-cuidados-capilares',
    hair_salon: 'saloes-de-cabelo',
    insurance_agency: 'agencias-de-seguros',
    laundry: 'lavanderias',
    lawyer: 'advogados',
    locksmith: 'chaveiros',
    makeup_artist: 'maquiadores',
    moving_company: 'empresas-de-mudanca',
    nail_salon: 'saloes-de-unhas',
    painter: 'pintores',
    plumber: 'encanadores',
    psychic: 'videntes',
    real_estate_agency: 'imobiliarias',
    roofing_contractor: 'empreiteiros-de-telhados',
    storage: 'depositos',
    summer_camp_organizer: 'organizadores-de-acampamento-de-verao',
    tailor: 'alfaiates',
    telecommunications_service_provider: 'provedores-de-telecomunicacoes',
    tour_agency: 'agencias-de-turismo',
    tourist_information_center: 'centros-de-informacao-turistica',
    travel_agency: 'agencias-de-viagens',
    veterinary_care: 'clinicas-veterinarias',

    // hospedagem
    bed_and_breakfast: 'pousadas-com-cafe',
    budget_japanese_inn: 'pousadas-japonesas-economicas',
    chalet: 'chales',
    campground: 'campings',
    camping_cabin: 'cabanas-de-camping',
    cottage: 'chalezinhos',
    extended_stay_hotel: 'hoteis-de-longa-estadia',
    farmstay: 'hospedagens-em-fazenda',
    guest_house: 'casas-de-hospedes',
    hostel: 'hostels',
    hotel: 'hoteis',
    inn: 'pousadas',
    japanese_inn: 'pousadas-japonesas',
    lodging: 'hospedagens',
    mobile_home_park: 'parques-de-trailers',
    motel: 'moteis',
    private_guest_room: 'quartos-privados-para-hospedes',
    resort_hotel: 'hoteis-resort',
    rv_park: 'parques-para-motorhomes',

    // recursos naturais
    beach: 'praias',

    // locais de culto
    church: 'igrejas',
    hindu_temple: 'templos-hindus',
    mosque: 'mesquitas',
    synagogue: 'sinagogas',

    // areas geograficas
    administrative_area_level_1: 'areas-administrativas-nivel-1',
    administrative_area_level_2: 'areas-administrativas-nivel-2',
    country: 'paises',
    locality: 'localidades',
    postal_code: 'codigos-postais',
    school_district: 'distritos-escolares',

    // governo
    city_hall: 'prefeituras',
    courthouse: 'tribunais',
    embassy: 'embaixadas',
    fire_station: 'quarteis-de-bombeiros',
    government_office: 'reparticoes-publicas',
    local_government_office: 'reparticoes-do-governo-local',
    neighborhood_police_station: 'delegacias-de-bairro',
    police: 'delegacias',
    post_office: 'correios',

    // saude e bem-estar
    alternative_medicine: 'centros-de-medicina-alternativa',
    psychotherapist: 'psicoterapeutas',
    chiropractor: 'quiropatas',
    clinic: 'clinicas',
    dental_clinic: 'clinicas-dentarias',
    dentist: 'dentistas',
    doctor: 'medicos',
    drugstore: 'drogarias',
    hospital: 'hospitais',
    massage: 'centros-de-massagem',
    medical_lab: 'laboratorios-medicos',
    pharmacy: 'farmacias',
    physiotherapist: 'fisioterapeutas',
    sauna: 'saunas',
    skin_care_clinic: 'clinicas-de-dermatologia',
    spa: 'spas',
    tanning_studio: 'centros-de-bronzeamento',
    wellness_center: 'centros-de-bem-estar',
    yoga_studio: 'estudios-de-yoga',

    // moradia
    apartment_building: 'edificios-residenciais',
    apartment_complex: 'complexos-de-apartamentos',
    condominium_complex: 'condominios',
    housing_complex: 'conjuntos-habitacionais',

    // gastronomia
    acai_shop: 'lojas-de-acai',
    afghani_restaurant: 'restaurantes-afegaos',
    african_restaurant: 'restaurantes-africanos',
    american_restaurant: 'restaurantes-americanos',
    asian_restaurant: 'restaurantes-asiaticos',
    bagel_shop: 'lojas-de-bagels',
    bakery: 'padarias',
    bar: 'bares',
    bar_and_grill: 'bares-e-churrasquerias',
    barbecue_restaurant: 'churrascarias',
    brazilian_restaurant: 'restaurantes-brasileiros',
    breakfast_restaurant: 'restaurantes-de-cafe-da-manha',
    brunch_restaurant: 'restaurantes-de-brunch',
    buffet_restaurant: 'restaurantes-buffet',
    cafe: 'cafes',
    cafeteria: 'cafeterias',
    candy_store: 'lojas-de-doces',
    cat_cafe: 'cat-cafes',
    chinese_restaurant: 'restaurantes-chineses',
    chocolate_factory: 'fabricas-de-chocolate',
    chocolate_shop: 'lojas-de-chocolate',
    coffee_shop: 'cafeterias',
    confectionery: 'confeitarias',
    deli: 'delicatessens',
    dessert_restaurant: 'restaurantes-de-sobremesas',
    dessert_shop: 'lojas-de-sobremesas',
    diner: 'lanchonetes',
    dog_cafe: 'dog-cafes',
    donut_shop: 'lojas-de-donuts',
    fast_food_restaurant: 'restaurantes-de-fast-food',
    fine_dining_restaurant: 'restaurantes-de-alta-gastronomia',
    food_court: 'pracas-de-alimentacao',
    french_restaurant: 'restaurantes-franceses',
    greek_restaurant: 'restaurantes-gregos',
    hamburger_restaurant: 'hamburguerias',
    ice_cream_shop: 'sorveterias',
    indian_restaurant: 'restaurantes-indianos',
    indonesian_restaurant: 'restaurantes-indonesios',
    italian_restaurant: 'restaurantes-italianos',
    japanese_restaurant: 'restaurantes-japoneses',
    juice_shop: 'lojas-de-sucos',
    korean_restaurant: 'restaurantes-coreanos',
    lebanese_restaurant: 'restaurantes-libaneses',
    meal_delivery: 'servicos-de-delivery-de-refeicoes',
    meal_takeaway: 'locais-de-comida-para-viagem',
    mediterranean_restaurant: 'restaurantes-mediterraneos',
    mexican_restaurant: 'restaurantes-mexicanos',
    middle_eastern_restaurant: 'restaurantes-do-oriente-medio',
    pizza_restaurant: 'pizzarias',
    pub: 'pubs',
    ramen_restaurant: 'restaurantes-de-ramen',
    restaurant: 'restaurantes',
    sandwich_shop: 'lojas-de-sanduiches',
    seafood_restaurant: 'restaurantes-de-frutos-do-mar',
    spanish_restaurant: 'restaurantes-espanhois',
    steak_house: 'churrascarias',
    sushi_restaurant: 'restaurantes-de-sushi',
    tea_house: 'casas-de-cha',
    thai_restaurant: 'restaurantes-tailandeses',
    turkish_restaurant: 'restaurantes-turcos',
    vegan_restaurant: 'restaurantes-veganos',
    vegetarian_restaurant: 'restaurantes-vegetarianos',
    vietnamese_restaurant: 'restaurantes-vietnamitas',
    wine_bar: 'bares-de-vinho',

    // === Instalacoes ===
    public_bath: 'banhos-publicos',
    public_bathroom: 'banheiros-publicos',
    stable: 'estabulos',

    // === Financas ===
    accounting: 'servicos-de-contabilidade',
    atm: 'caixas-eletronicos',
    bank: 'bancos',
    currency_exchange: 'casas-de-cambio',

    // === Entretenimento e Recreacao ===
    adventure_sports_center: 'centros-de-esportes-de-aventura',
    amphitheatre: 'anfiteatros',
    amusement_center: 'centros-de-diversao',
    amusement_park: 'parques-de-diversoes',
    aquarium: 'aquarios',
    banquet_hall: 'saloes-de-festas',
    barbecue_area: 'areas-de-churrasco',
    botanical_garden: 'jardins-botanicos',
    bowling_alley: 'pistas-de-boliche',
    casino: 'cassinos',
    childrens_camp: 'acampamentos-infantis',
    comedy_club: 'clubes-de-comedia',
    community_center: 'centros-comunitarios',
    concert_hall: 'salas-de-concerto',
    convention_center: 'centros-de-convencoes',
    cultural_center: 'centros-culturais',
    cycling_park: 'parques-para-ciclismo',
    dance_hall: 'saloes-de-danca',
    dog_park: 'parques-para-caes',
    event_venue: 'espacos-para-eventos',
    ferris_wheel: 'rodas-gigantes',
    garden: 'jardins',
    hiking_area: 'areas-de-trilha',
    historical_landmark: 'marcos-historicos',
    internet_cafe: 'lan-houses',
    karaoke: 'karaokes',
    marina: 'marinas',
    movie_rental: 'locadoras-de-filmes',
    movie_theater: 'cinemas',
    national_park: 'parques-nacionais',
    night_club: 'casas-noturnas',
    observation_deck: 'mirantes',
    off_roading_area: 'areas-de-off-road',
    opera_house: 'casas-de-opera',
    park: 'parques',
    philharmonic_hall: 'salas-filarmonicas',
    picnic_ground: 'areas-de-piquenique',
    planetarium: 'planetarios',
    plaza: 'pracas',
    roller_coaster: 'montanhas-russas',
    skateboard_park: 'pistas-de-skate',
    state_park: 'parques-estaduais',
    tourist_attraction: 'atracoes-turisticas',
    video_arcade: 'fliperama',
    visitor_center: 'centros-de-visitantes',
    water_park: 'parques-aquaticos',
    wedding_venue: 'espacos-para-casamentos',
    wildlife_park: 'parques-de-vida-selvagem',
    wildlife_refuge: 'refugios-de-vida-selvagem',
    zoo: 'zoologicos',

    // === Negocios ===
    corporate_office: 'escritorios-corporativos',
    farm: 'fazendas',
    ranch: 'ranchos',
    coworking_space: 'espacos-de-coworking',

    // === Cultura ===
    art_gallery: 'galerias-de-arte',
    art_studio: 'atelieres',
    auditorium: 'auditorios',
    cultural_landmark: 'marcos-culturais',
    historical_place: 'lugares-historicos',
    monument: 'monumentos',
    museum: 'museus',
    performing_arts_theater: 'teatros-de-artes-cenicas',
    sculpture: 'esculturas',

    // === Educacao ===
    library: 'bibliotecas',
    preschool: 'pre-escolas',
    primary_school: 'escolas-primarias',
    school: 'escolas',
    secondary_school: 'escolas-secundarias',
    university: 'universidades',
    music_school: 'escolas-de-musica',
    driving_school: 'autoescolas',
    cooking_school: 'escolas-de-culinaria',

    // === Automotivo ===
    bicycle_rental: 'aluguel-de-bicicletas',
    car_dealer: 'concessionarias',
    car_rental: 'locadoras-de-veiculos',
    car_repair: 'oficinas-mecanicas',
    car_wash: 'lava-rapidos',
    electric_vehicle_charging_station: 'estacoes-de-recarga-de-veiculos-eletricos',
    gas_station: 'postos-de-combustivel',
    parking: 'estacionamentos',
    rest_stop: 'areas-de-descanso',

    // outro
    other: 'outros',
};

export const SUBCATEGORY_SLUGS_BY_LOCALE: Partial<Record<Locale, Record<PlaceSubcategory, string>>> & { en: Record<PlaceSubcategory, string> } = {
    'en': SUBCATEGORY_EN_SLUG_MAP,
    'es': SUBCATEGORY_ES_SLUG_MAP,
    'pt': SUBCATEGORY_PT_SLUG_MAP,
}

// Reverse lookup: from slug to subcategory
const EN_SLUG_TO_SUBCATEGORY: Record<string, PlaceSubcategory> = Object.fromEntries(
    Object.entries(SUBCATEGORY_EN_SLUG_MAP).map(([key, value]) => [value, key as PlaceSubcategory])
);

const ES_SLUG_TO_SUBCATEGORY: Record<string, PlaceSubcategory> = Object.fromEntries(
    Object.entries(SUBCATEGORY_ES_SLUG_MAP).map(([key, value]) => [value, key as PlaceSubcategory])
);

const PT_SLUG_TO_SUBCATEGORY: Record<string, PlaceSubcategory> = Object.fromEntries(
    Object.entries(SUBCATEGORY_PT_SLUG_MAP).map(([key, value]) => [value, key as PlaceSubcategory])
);

/**
 * Get the subcategory from a plural slug (e.g., "atms" -> "atm", "restaurants" -> "restaurant")
 */
export function getSubcategoryFromSlug(slug: string, locale: string = 'en'): PlaceSubcategory | null {
    let map: Record<string, PlaceSubcategory>;
    switch (locale) {
        case 'es': map = ES_SLUG_TO_SUBCATEGORY; break;
        case 'pt': map = PT_SLUG_TO_SUBCATEGORY; break;
        default: map = EN_SLUG_TO_SUBCATEGORY; break;
    }
    return map[slug] || null;
}

export function getLocalizedCountryCategorySlug(countryName: string, subcategory: PlaceSubcategory, locale: string = 'en'): string {
    const slug = getSimplifiedCountrySlug(countryName)
    switch (locale) {
        case 'es': return `${SUBCATEGORY_ES_SLUG_MAP[subcategory]}-bitcoin-en-${slug}`;
        case 'pt': return `${SUBCATEGORY_PT_SLUG_MAP[subcategory]}-bitcoin-em-${slug}`;
        default: return `bitcoin-${SUBCATEGORY_EN_SLUG_MAP[subcategory]}-in-${slug}`;
    }
}


export function getLocalizedCitySlug(countryName: string, cityName: string, locale: string = 'en'): string {
    const slug = getSimplifiedCitySlug(countryName, cityName)
    switch (locale) {
        case 'es': return `lugares-bitcoin-en-${slug}`;
        case 'pt': return `locais-bitcoin-em-${slug}`;
        default: return `bitcoin-shops-in-${slug}`;
    }
}

export function getLocalizedCityCategorySlug(countryName: string, cityName: string, subcategory: PlaceSubcategory, locale: string = 'en'): string {
    const citySlug = getSimplifiedCitySlug(countryName, cityName);
    switch (locale) {
        case 'es': return `${SUBCATEGORY_ES_SLUG_MAP[subcategory]}-bitcoin-en-${citySlug}`;
        case 'pt': return `${SUBCATEGORY_PT_SLUG_MAP[subcategory]}-bitcoin-em-${citySlug}`;
        default: return `bitcoin-${SUBCATEGORY_EN_SLUG_MAP[subcategory]}-in-${citySlug}`;
    }
}
