/**
 * Validates that all slug generation functions produce URLs that
 * actually exist in venue_slug_map.json. Catches mismatches between
 * SlugUtils.ts functions and the data generated by MerchantSlugs.ts.
 */
import fs from 'fs';
import path from 'path';

// Import slug generation functions
import { getLocalizedCountrySlug, getLocalizedCitySlug, getLocalizedCountryCategorySlug, getLocalizedCityCategorySlug } from '../utils/SlugUtils';
import { getLocalizedCountryName } from '../utils/CountryUtils';

const DATA_DIR = path.join(__dirname, '..', 'data');

type SlugEntry = {
    type: string;
    canonical: string;
    alternates?: Record<string, string>;
    country?: string;
    location?: string;
    categoryAndSubcategory?: { category: string; subcategory: string };
};

async function main() {
    // Load slug data
    const slugMap: Record<string, SlugEntry> = JSON.parse(
        fs.readFileSync(path.join(DATA_DIR, 'venue_slug_map.json'), 'utf-8')
    );
    const merchantSlugs: SlugEntry[] = JSON.parse(
        fs.readFileSync(path.join(DATA_DIR, 'merchant-slugs.json'), 'utf-8')
    );

    // Build a set of all valid slugs (lowercase)
    const validSlugs = new Set<string>();
    for (const key of Object.keys(slugMap)) {
        validSlugs.add(key.toLowerCase());
    }
    // Also add alternates from merchant-slugs
    for (const entry of merchantSlugs) {
        if (entry.alternates) {
            for (const alt of Object.values(entry.alternates)) {
                // Strip locale prefix (e.g., "es/slug" → "slug")
                const stripped = alt.replace(/^(es|pt)\//, '');
                validSlugs.add(stripped.toLowerCase());
            }
        }
        if (entry.canonical) {
            validSlugs.add(entry.canonical.toLowerCase());
        }
    }

    console.log(`\nLoaded ${validSlugs.size} valid slugs from data files.\n`);

    const locales = ['en', 'es', 'pt'] as const;
    const errors: { generated: string; locale: string; type: string; inputs: string }[] = [];
    let totalChecked = 0;

    // Collect unique countries and cities from the data
    const countryCodes = new Set<string>();
    const cityCountryPairs: { city: string; country: string }[] = [];
    const categoryCountryPairs: { subcategory: string; country: string }[] = [];
    const categoryCityPairs: { subcategory: string; city: string; country: string }[] = [];

    for (const entry of merchantSlugs) {
        if (entry.country) countryCodes.add(entry.country);
    }

    // For each entry in venue_slug_map, extract the structure
    for (const [slug, entry] of Object.entries(slugMap)) {
        if (entry.country) countryCodes.add(entry.country);
        if (entry.type === 'city' && entry.location && entry.country) {
            cityCountryPairs.push({ city: entry.location, country: entry.country });
        }
        if (entry.type === 'category' && entry.country && entry.categoryAndSubcategory) {
            if (entry.location) {
                categoryCityPairs.push({
                    subcategory: entry.categoryAndSubcategory.subcategory,
                    city: entry.location,
                    country: entry.country
                });
            } else {
                categoryCountryPairs.push({
                    subcategory: entry.categoryAndSubcategory.subcategory,
                    country: entry.country
                });
            }
        }
    }

    console.log(`Countries: ${countryCodes.size}`);
    console.log(`City/state pages: ${cityCountryPairs.length}`);
    console.log(`Country+category pages: ${categoryCountryPairs.length}`);
    console.log(`City+category pages: ${categoryCityPairs.length}`);
    console.log('');

    // 1. Test country slugs
    console.log('--- Testing country slugs ---');
    for (const code of countryCodes) {
        for (const locale of locales) {
            const countryName = getLocalizedCountryName(locale, code);
            if (!countryName) continue;
            const generated = getLocalizedCountrySlug(countryName, locale).toLowerCase();
            totalChecked++;
            if (!validSlugs.has(generated)) {
                errors.push({ generated, locale, type: 'country', inputs: `${code} (${countryName})` });
            }
        }
    }

    // 2. Test city/state slugs (sample — check up to 200)
    console.log('--- Testing city/state slugs ---');
    const citySample = cityCountryPairs.slice(0, 200);
    for (const { city, country } of citySample) {
        for (const locale of locales) {
            const countryName = getLocalizedCountryName(locale, country);
            if (!countryName) continue;
            const generated = getLocalizedCitySlug(countryName, city, locale).toLowerCase();
            totalChecked++;
            if (!validSlugs.has(generated)) {
                errors.push({ generated, locale, type: 'city', inputs: `${city}, ${country} (${countryName})` });
            }
        }
    }

    // 3. Test country+category slugs (sample — check up to 200)
    console.log('--- Testing country+category slugs ---');
    const catCountrySample = categoryCountryPairs.slice(0, 200);
    for (const { subcategory, country } of catCountrySample) {
        for (const locale of locales) {
            const countryName = getLocalizedCountryName(locale, country);
            if (!countryName) continue;
            try {
                const generated = getLocalizedCountryCategorySlug(countryName, subcategory as any, locale).toLowerCase();
                totalChecked++;
                if (!validSlugs.has(generated)) {
                    errors.push({ generated, locale, type: 'country+category', inputs: `${subcategory} in ${country} (${countryName})` });
                }
            } catch {
                // Skip subcategories not in the slug map
            }
        }
    }

    // 4. Test city+category slugs (sample — check up to 200)
    console.log('--- Testing city+category slugs ---');
    const catCitySample = categoryCityPairs.slice(0, 200);
    for (const { subcategory, city, country } of catCitySample) {
        for (const locale of locales) {
            const countryName = getLocalizedCountryName(locale, country);
            if (!countryName) continue;
            try {
                const generated = getLocalizedCityCategorySlug(countryName, city, subcategory as any, locale).toLowerCase();
                totalChecked++;
                if (!validSlugs.has(generated)) {
                    errors.push({ generated, locale, type: 'city+category', inputs: `${subcategory} in ${city}, ${country} (${countryName})` });
                }
            } catch {
                // Skip subcategories not in the slug map
            }
        }
    }

    // Report
    console.log('\n========================================');
    console.log('  SLUG VALIDATION REPORT');
    console.log('========================================\n');
    console.log(`Total slugs checked: ${totalChecked}`);
    console.log(`Broken slugs found:  ${errors.length}`);

    if (errors.length > 0) {
        console.log('\n--- BROKEN SLUGS ---\n');
        // Group by type
        const byType = new Map<string, typeof errors>();
        for (const err of errors) {
            const list = byType.get(err.type) || [];
            list.push(err);
            byType.set(err.type, list);
        }
        for (const [type, errs] of byType) {
            console.log(`\n[${type}] — ${errs.length} broken:`);
            for (const err of errs.slice(0, 20)) {
                console.log(`  ${err.locale}: /${err.generated}`);
                console.log(`    Inputs: ${err.inputs}`);
            }
            if (errs.length > 20) {
                console.log(`  ... and ${errs.length - 20} more`);
            }
        }
    } else {
        console.log('\n✓ All generated slugs match the data files.');
    }

    console.log('');
    process.exit(errors.length > 0 ? 1 : 0);
}

main().catch(console.error);
